name: RWorld
main: cn.mclover.mc.rworld.Main
softdepend: [Multiverse-Core, MultiWorld, LWC]
version: 2.2
author: wahoo
website: www.mclover.cn
description: Auto reflesh world at night
commands:
   refresh:
      description: help
      usage: /refresh 
permissions:
    refresh:
        description: refresh world commands
        default: op